### ISSUE TITLE
小目标的一个问题

### ISSUE THREAD

**Issue by heartInsert** [Captain1986/CaptainBlackboard#122]
作者你好，看到你发的深度学习小目标中关于复制粘贴更多的小目标的方式，我觉得很不错，有代码可以让我看看吗？
谢谢

Captain ,　我从小学就开始看海贼了，看到了现在，看在这个份上，回我一下呗。

**Comment by Captain1986** [comment]
GitHub上应该有不少这样的小工具，比如这个https://github.com/maozezhong/CV_ToolBox；另外也可以自己实现一个贡献给开源社区哈；实现时不要直接cut&paste，可以在边缘用一下融合技巧，比如alpha加权或者复杂点的泊松融合

**Comment by Captain1986** [comment]
GitHub上应该有不少这样的小工具，比如这个https://github.com/maozezhong/CV_ToolBox；
另外也可以自己实现一个贡献给开源社区哈；实现时不要直接cut&paste，可以在边缘用一下融合技巧，比如alpha加权或者复杂点的泊松融合
